
package NerdleGame;

import java.io.File;
import javax.swing.JPanel;
/**
 *
 * @author Muhammed Ali
 */
public class Menu extends JPanel{

    private Nerdle window;

    /**
     * Creates new form Menu
     */
    public Menu() {
    }

    public Menu(Nerdle window) {
        // javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        initComponents();
        init();
        this.window = window;
    }
    
    private void init(){
        checkRecordFile();
        getStatics();
    }
    
   
   public void checkRecordFile(){
       File myFile = new File("records.dat");
        if(!myFile.exists())
            devamButton.setVisible(false);
        else
            devamButton.setVisible(true);
   }
   
   public boolean checkStatFile(){
       File myFile = new File("statics.dat");
        return myFile.exists();
   }
   
   public void getStatics(){
      if(checkStatFile()){
          Statics stat=FileOperations.readStatics();
        labelTotal.setText("Oynanan Toplam Oyun Sayısı: "+stat.getTotalGames());
        labelWin.setText("Kazanılan Oyun Sayısı: "+stat.getWinGames());
        labelLost.setText("Kaybedilen Oyun Sayısı: "+stat.getLostGames());
        labelUnf.setText("Yarım Bırakılmış Oyun Sayısı: "+stat.getUnfinishedGames());
        labelRow.setText(String.format("Ortalama Satır: %.2f", stat.getAverageRowNumber()));
        labelTime.setText(String.format("Ortalama Süre: %.1f saniye",stat.getAverageTime()));
      }
   }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devamButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        newGameButton = new javax.swing.JButton();
        labelTime = new javax.swing.JLabel();
        labelRow = new javax.swing.JLabel();
        labelUnf = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        labelWin = new javax.swing.JLabel();
        labelLost = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        devamButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        devamButton.setText("DEVAM ET");
        devamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devamButtonActionPerformed(evt);
            }
        });

        testButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        testButton.setText("TEST");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        newGameButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        newGameButton.setText("YENİ OYUN");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        labelTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTime.setText("Ortalama Süre: 0");

        labelRow.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRow.setText("Ortalama Satır Sayısı : 0");

        labelUnf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelUnf.setText("Yarım Bırakılmış Oyun Sayısı: 0");

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTitle.setText("Geçmiş Oyunların İstatistikleri");

        labelWin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelWin.setText("Kazanılan Oyun Sayısı: 0");

        labelLost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLost.setText("Kaybedilen Oyun Sayısı: 0");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTotal.setText("Toplam Oyun Sayısı: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(522, 522, 522)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(devamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUnf, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRow, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelLost, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelWin, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal)
                .addGap(4, 4, 4)
                .addComponent(labelWin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUnf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(devamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void devamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devamButtonActionPerformed
        window.devamEt();
    }//GEN-LAST:event_devamButtonActionPerformed
    
    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        window.newGame();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        window.goTest();
    }//GEN-LAST:event_testButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devamButton;
    private javax.swing.JLabel labelLost;
    private javax.swing.JLabel labelRow;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelUnf;
    private javax.swing.JLabel labelWin;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables
}
