/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NerdleGame;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author Muhammed Ali
 */
public class Test extends javax.swing.JPanel {
    private Blocks blocks[];
    private String equation;
    private Equation eqObj = new Equation();
    private int lenght;
    private JPanel panel = new JPanel();
    private Nerdle window;
    /**
     * Creates new form Test
     */
    public Test(Nerdle window) {
        this.window = window;
        initComponents();
        init();
    }
    
    private void init(){
        panel.setLayout(null);
        panel.setBounds(250, 180,780, 360);
        add(panel);
        equation = eqObj.generateEquation();
        lenght = equation.length();
        addBoard();
    }
    
     public void addBoard(){
        Blocks blocks[] = new Blocks[9];
            for(int j = 0 ; j < lenght ; j++) {
                blocks[j] = new Blocks(90 + 70*j, 150 + 70*0); 
                panel.add(blocks[j].getDisplay());
                blocks[j].setChar(equation.charAt(j));
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testbutton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        testbutton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        testbutton.setText("YENİ DENKLEM ÜRET");
        testbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testbuttonActionPerformed(evt);
            }
        });

        returnButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        returnButton.setText("ANA MENÜYE DÖN");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(452, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(testbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(439, 439, 439))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(478, Short.MAX_VALUE)
                .addComponent(testbutton)
                .addGap(32, 32, 32)
                .addComponent(returnButton)
                .addGap(102, 102, 102))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void testbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testbuttonActionPerformed
        panel.removeAll();
        this.repaint();
        equation = eqObj.generateEquation();
        lenght = equation.length();
        addBoard();
    }//GEN-LAST:event_testbuttonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        window.returnToMenu(this);
    }//GEN-LAST:event_returnButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton returnButton;
    private javax.swing.JButton testbutton;
    // End of variables declaration//GEN-END:variables
}
